### ISSUE TITLE
Datepicker spans all the way to the left border of the viewport in right-to-left languages

### ISSUE THREAD

**Issue by kolingua** [uxsolutions/bootstrap-datepicker#1321]
![dp_ar](https://cloud.githubusercontent.com/assets/11250000/6708450/a316c0e8-cd70-11e4-9432-2dafc3a8a919.png)

**Comment by acrobat** [comment]
@kolingua can you provide a jsfiddle example? (you can use [this jsfiddle](http://jsfiddle.net/vh1oknf7/) as a base example)

**Comment by kolingua** [comment]
@acrobat, the jsfiddle you linked to seems to ignore any language specification. 
But now I'm wondering if this is a real issue. I wast just playing with the sandbox, and maybe the problem comes from trying to use a right-to-left datepicker on a left-to-right page, and would not occur on a real page fully written in Arabic and with a global right-to-left setup.

**Comment by rhoggSugarcrm** [comment]
IMO even in the case of a page with mixed-direction content, the span shouldn't do that. It should match the size of the calendar.

I've tried this with the sandbox using version 1.4 and this happens for me. Also, on my company's private project we get an even stranger variant of this problem with version 1.3: if you click on the whitespace part of the span, it gets bigger. Keep doing this and it eventually fills the entire horizontal space of the browser window. (The problem seems to be calculation of the `left` CSS rule in version 1.3 - it gets subtracted from on each click. This has been fixed as of 1.4, although we still have other problems.)

@acrobat I'll see if I can construct some jsfiddles to demonstrate our problems. Will post again when they're done.

**Comment by rhoggSugarcrm** [comment]
For 1.4, I found that adding `left: right - width,` to the CSS worked for text input. Doesn't help at all for component mode though - it's all the way off to the right side of the page, far away from the text box.

**Comment by rhoggSugarcrm** [comment]
I suspect that at least part of the problem is here: https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L685

```js
var width = this.component ? this.component.outerWidth(true) : this.element.outerWidth(false);
```

In component mode this means that width (which is used in the calculation of right) does not include the width of the text input, just the width of the calendar icon add-on. 

In my opinion this should probably be something like 
```js
var width = this.component ? this.component.outerWidth(true) + this.element.outerWidth(false) : this.element.outerWidth(false);
```
so that we include the width of the text box.

Thoughts @acrobat?

**Comment by acrobat** [comment]
I currently don't  have the time to look in detail into this issue. But looks like this might fix it, can you sumbit a PR for this and test it (maybe add a unit test too or so)

**Comment by rhoggSugarcrm** [comment]
I'll try to work on it today. No promises though, I am also rather busy. My apologies

**Comment by rhoggSugarcrm** [comment]
I'm opening a work-in-progress PR so you can keep track of the work. Currently I've fixed Arabic with text inputs and auto orientation, which is a lot better, but for component inputs and/or forced-right orientation it's still completely wrong.

**Comment by rhoggSugarcrm** [comment]
Code in the above PR is ready. No tests yet though - I'll work on them.

As I said in the above PR, I didn't fix it for Range-type inputs. We don't use those, so I can't justify spending the time on them, sorry.

**Comment by asmaazoghbi** [comment]
@rhoggSugarcrm  is the issue solved? I tried the changes done in #1384 but the problem is not solved.
Please any suggestions to solve this issue?

**Comment by Azaret** [comment]
This will be fixed in `1.7.0`
