### ISSUE TITLE
Keyboard navigation jump back

### ISSUE THREAD

**Issue by JammySlayer** [uxsolutions/bootstrap-datepicker#2046]
### Expected behaviour
When holding ctrl/shift you can navigate through year/month, when you then release ctrl/shift it should remain on the selected year/month

### Actual behaviour
Jumps back to current or previously input date

### Datepicker version used
Which ever is used on the demo, also present in 1.5.1

### Example code
Just use the demo

**Comment by Azaret** [comment]
Try to set `updateViewDate` to false, it should solve this issue.
I let this as an issue as `updateViewDate` should be false by default.

**Comment by acrobat** [comment]
@Azaret how can `updateViewDate` be the problem? As this was merged in 1.7.0 and it is already a bug in 1.6.4

**Comment by Azaret** [comment]
Ahmm, well I guess the issue was solved in the `1.7` but `updateViewDate` broke it back, if you do set it to false the issue is gone. I didn't make an expensive research on the changes in `1.7` that has solve this issue but I can look at it this weekend.

**Comment by orioljd** [comment]
This is still happening in 1.8, there are plans to solve it?

**Comment by iameddz** [comment]
is there any other workaround with less side-effects than 'updateViewDate'?
