### ISSUE TITLE
1.7.0 moved jQuery to peerDependencies which is a breaking change

### ISSUE THREAD

**Issue by andreypopp** [uxsolutions/bootstrap-datepicker#2206]
### Expected behaviour
`npm install bootstrap-datepicker@^1.0.0` should install jQuery as its own dependency as before

### Actual behaviour
`npm install bootstrap-datepicker@^1.0.0` instead doesn't install jQuery as it is moved to `peerDependencies` which broke our already released versions of packages which depend on `bootstrap-datepicker`.

**Comment by andreypopp** [comment]
Change was made in https://github.com/uxsolutions/bootstrap-datepicker/commit/84e96f469dd53484d04163a20722c85b30bf4324 cc @Mithgol who authored the commit.

**Comment by acrobat** [comment]
@andreypopp you can check the discussion about this change in #2163

It's possible to revert this change, but I merged by the discussion in the PR, so the fix looked good

**Comment by andreypopp** [comment]
Hm... I still consider moving to peerDependencies a breaking change as it requires changes in consumer code.

It's up to you to decide but considering that releasing 2.0.0 requires low effort — why not doing that instead?

**Comment by acrobat** [comment]
I did not know this would introduce a bc break from the description in the PR. I would go for reverting it in 1.7.x and re-introduce if necessary in 2.0

What do you think @andreypopp and @Mithgol

**Comment by andreypopp** [comment]
That would be great!

**Comment by Mithgol** [comment]
I feel fine about reverting it in 1.7.x and re-introducing in 2.0.

**Comment by andreypopp** [comment]
Awesome! Can this be released as 1.7.1?

**Comment by acrobat** [comment]
I will try to push a new release later tonight or tomorrow!

**Comment by acrobat** [comment]
@andreypopp I've pushed a new release (1.7.1)

**Comment by andreypopp** [comment]
Thank you!

**Comment by einfallstoll** [comment]
What's the status here? 2.0.0 is still not released, but I think moving jQuery to `peerDependencies` makes sense as stated in #2399. Could we publish 2.0.0 early and move the remaining breaking changes to 3.0.0?

**Comment by setefocos** [comment]
It is breaking with Webpack. that is instantiating a new jquery object just for jQuery-slimScroll. The jquery instance of our project ends with no .slimscroll function. "peerDependencies" solves that. Please update package.json! It requires a major version bump, because it forces projects that uses jQuery-slimScroll to have jquery dependencie declared on the own package.json.

In my opinion, a lot of people is doing an ungly workround do deal with it, since webpack is the most used build tool.
![image](https://user-images.githubusercontent.com/26557942/89703063-b4463380-d91d-11ea-9edd-ebf9bba21526.png)
[https://2019.stateofjs.com/other-tools/build_tools](url)
